allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.layout.buildDirectory = '../build'
subprojects {
    project.layout.buildDirectory = rootProject.layout.buildDirectory.dir(project.name)
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
